# Generated by Django 2.2.5 on 2020-02-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('benefit', models.CharField(max_length=1000)),
                ('explanation', models.CharField(max_length=2000)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('store', models.CharField(max_length=1000)),
                ('start', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
