version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      - "POSTGRES_PASSWORD=postgres"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5480:80"
    environment: 
      - "PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com"
      - "PGADMIN_DEFAULT_PASSWORD=pgadmin"
